site: Buster Benson
url: https://busterbenson.com
title: Buster Benson
description: My blog.
permalink: pretty

strict_front_matter: true
liquid:
  error_mode: strict
  
baseurl: ""

highlighter: none

exclude:
  - '.jekyll-cache'
  - 'Gemfile'
  - 'Gemfile.lock'
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style:    :compressed

target-blank:
  add_css_classes: external-link

picture:
  source: "/assets/images"
  suppress_warnings: true
  fast_build: development

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"