# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'notes'
    label: 'notes'
    folder: '_posts/'
    create: true
    path: '{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields: &basicpost  
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'me' }
      - { label: 'One-Liner', name: 'one_liner', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image', 
          media_library: { config: { multiple: true } } }
      - { label: 'Piles', name: 'piles', widget: 'list' }
      - { label: 'Redirect', name: 'redirect', widget: 'boolean', default: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
